### ISSUE TITLE
HTTP Connection

### ISSUE THREAD

**Issue by nguyenhuutinh** [AlexGilleran/IceSoap#1]
Hi Alex,

Thanks for your very useful library.
Currently, Android HTTP Connection using HttpClient/HttpPost have been deprecated.
Do you have plan for updating it?

I tried to use Retrofit but I cannot send a String or SOAPEnvelope object to server.
Server doesn't know it is a soap Object

**Comment by AlexGilleran** [comment]
I'll look into creating a new version targeting a higher API level, but I'm too busy at the moment to put any timeline on it.

Does this not allow it to run on Android 6?

```
android {
    useLibrary 'org.apache.http.legacy'
}
```

**Comment by AlexGilleran** [comment]
Working on this at the moment, will be doing Icesoap 2 with some breaking API changes to allow HttpURLConnection-based connections and ensure that they're closed at the end, and allow for opting in to concurrent AsyncTasks, should be done soon.

**Comment by AlexGilleran** [comment]
Fixed in 1.1.0
