### ISSUE TITLE
executeBlocking() not working

### ISSUE THREAD

**Issue by adnen-chouibi** [AlexGilleran/IceSoap#12]
I created a request and i used .executeBlocking()  But a NetworkOnMainThreadException occurred that says android.os.NetworkOnMainThreadException at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147).
 How could I solve this problem?

**Comment by AlexGilleran** [comment]
Ideally don't use `executeBlocking`on the UI thread - that call is more intended for situations where you've got your own AsyncTask or you're using it from within a service.

If you're really really really sure you can do this http://stackoverflow.com/a/9289190, but it'll result in the whole app locking up until the response comes back.
