### ISSUE TITLE
How to update DEFAULT_SOCKET_TIMEOUT for any request?

### ISSUE THREAD

**Issue by qdupendra** [AlexGilleran/IceSoap#18]
Hi, 
Is there a way we can update the timeout duration for any request?
I have looked around and located the variable DEFAULT_SOCKET_TIMEOUT in the HTTPDefaults class. But I couldn't find any way I can update the value stored in this variable. 
Please let me know if it is possible to change the timeout with the current version.

P.S. thanks for this great library, it really has been very helpful.

**Comment by AlexGilleran** [comment]
You should be able to extend `ApacheSOAPRequester`, then in your class override `buildHTTPClient` and supply whatever timeout you like :)

**Comment by qdupendra** [comment]
Hi Alex,

Thanks for the suggestion, but the silly followup question is how would Icesoap be able to use the extended class instead of the `ApacheSOAPRequester`.

**Comment by qdupendra** [comment]
Hi Alex, 
Thanks a lot for the tip. I was able to achieve this via that way.

Closing this issue.
