### ISSUE TITLE
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class

### ISSUE THREAD

**Issue by ulx** [AlexGilleran/IceSoap#3]
Hi!
I have problem use gradle plugin 2.0 and multidex
How can I fix this?

Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.jaxen.dom.DocumentNavigator$6) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.jaxen.dom.DocumentNavigator$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.

**Comment by AlexGilleran** [comment]
Well, if it's coming from proguard then apparently you can do this:

```
-keepattributes EnclosingMethod
```

Otherwise you'll have to wait a bit - it looks like it objects to one of the dependencies, Jaxen, being compiled to .class files with an old version of Java, so I'll have to either switch it for a newer version or if that doesn't work bring the source in and compile it directly.

**Comment by AlexGilleran** [comment]
Alternatively you might be able to use this to force an upgrade to Jaxen 1.1.6 but no promises: http://stackoverflow.com/questions/30728533/gradle-override-transitive-dependency-by-version-classifier

**Comment by AlexGilleran** [comment]
_also_ given that it's a warning it shouldn't actually be a problem unless you're doing reflection into Jaxen's classpath, which I hope you aren't...

**Comment by ulx** [comment]
I do not use proguard.

**Comment by ulx** [comment]
Jaxen uses reflection
https://github.com/codehaus/jaxen/blob/master/jaxen/src/java/main/org/jaxen/dom/NamespaceNode.java

`    public String lookupPrefix(String namespaceURI) {
        // This could be fully implemented even in Java 1.4. See
        // http://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/namespaces-algorithms.html#lookupNamespaceURIAlgo
        // It hardly seems worth the effort though.
        
        try {
            Class clazz = Node.class;
            Class[] argTypes = {String.class};
            Method lookupPrefix = clazz.getMethod("lookupPrefix", argTypes);
            String[] args = {namespaceURI};
            String result = (String) lookupPrefix.invoke(parent, args);
            return result;
        }
        catch (NoSuchMethodException ex) {
            throw new UnsupportedOperationException("Cannot lookup prefixes in DOM 2");
        }
        catch (InvocationTargetException ex) {
            throw new UnsupportedOperationException("Cannot lookup prefixes in DOM 2");
        }
        catch (IllegalAccessException ex) {
            throw new UnsupportedOperationException("Cannot lookup prefixes in DOM 2");
        }
        
    }`

**Comment by AlexGilleran** [comment]
Yep, but not on `DocumentNavigator`, so that warning is annoying but shouldn't actually be breaking your code, or am I missing something?

**Comment by ulx** [comment]
I do not like warnings.
They appeared after updating to 2.0 gradle plugin

**Comment by AlexGilleran** [comment]
The warning should still definitely be fixed, I'll leave this open until I get around to upgrading jaxen :)

**Comment by ulx** [comment]
Thanks))

**Comment by AlexGilleran** [comment]
Fixed in 1.1.1

**Comment by ulx** [comment]
Great!
