### ISSUE TITLE
setDebugMode(true) not working

### ISSUE THREAD

**Issue by beta** [AlexGilleran/IceSoap#8]
I created a request and used `request.setDebugMode(true)` to activate debug mode. But when I called `Log.i("request", request.getRequestXML())` a NullPointerException occurred that says "println needs a message", which means the `getRequestXML()` returned `null`. It used to work, but since some time the debug mode seems not to be working any more. How could I solve this problem?

**Comment by AlexGilleran** [comment]
That's curious - do you know what the last version was that worked? Does this happen for all requests?

**Comment by beta** [comment]
@AlexGilleran I've figured out why it would fail. I called `getRequestXML` directly after the request instance is created. After moving this line into the observer of the `execute` method it works perfectly.

I used to think the XML should have been usable after the request is created. :(

**Comment by AlexGilleran** [comment]
Ah OK. It's been years since I wrote the code but I suspect maybe it only does the serialization of the envelope at the last moment before it's sent, so there's no string there yet.

I'll see about making it accessible earlier - at the very least it should be documented and not throw an NPE...

**Comment by beta** [comment]
It's not a big problem though. Thanks for your work!

**Comment by AlexGilleran** [comment]
I'll leave it open - I definitely need to fix the NullPointerException at the very least!

Thanks so much for the debugging :)

**Comment by pzienowicz** [comment]
I also receive NullPointerException but on onCompletion function.
I also noticed that onCompletion is fired after onException (when exception occurred).

**Comment by beta** [comment]
@pzienowicz Yes and I figured out that `if (request.getResult() != null)` should always be checked in `onCompletion` before any actions on the request result to make sure the request is successful.
