### ISSUE TITLE
Building the Envelope

### ISSUE THREAD

**Issue by wbhakti** [AlexGilleran/IceSoap#9]
How to create node when parameters value is byte, example like this 
![capture](https://cloud.githubusercontent.com/assets/7830019/16326413/98f3426a-39f0-11e6-90be-d6221bac8e29.PNG)
.
Thank's

**Comment by AlexGilleran** [comment]
That looks like a normal text node - you should be able to [convert the byte into base64](http://stackoverflow.com/questions/4838464/convert-byte-to-base64-string-for-data-uri) and [add the result to the envelope as normal](https://github.com/AlexGilleran/IceSoap/wiki/Getting-Started-%282%29).
